version: '2'

services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy-ex
        ports:
          - "81:80"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
    db:
        image: mysql
        container_name: "db"
        volumes:
            - ./ci/.data/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: "sf"
            MYSQL_ROOT_PASSWORD: "root"
    php:
        build: ./ci/php7-fpm-browserify
        container_name: "php7"
        links:
            - db:mysqldb
            - redis
        volumes:
            - ./:/var/www/symfony
            - /home/commposer/.composer/cache/:/root/.composer/cache/
            - ./ci/php7-fpm-browserify/config/php.ini:/usr/local/etc/php/php.ini
        expose:
            - 9901
    nginx:
        build: ./ci/nginx
        container_name: "server-ex"
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./ci/logs/nginx/:/var/log/nginx
        environment:
            - VIRTUAL_HOST=127.0.0.1
    redis:
        image: redis:latest
        ports:
            - 6381:6381